WIP: Project for house automation in Common Lisp: House automation bus (hab)

*** House Automation for Common Lisp

****  Motivation

I use home automation in my home. Currently utilizing [[https://www.openhab.org/][openHAB]]. While openHAB has many features and supports many devices and so on, it is also a heavy beast.

So my aim was to eventually replace openHAB. There are a few things still missing to do this. The current state of the cl-hab project lacks the following for me to be able to replace openHAB:

- support for KNX
- a REST interface
- a UI to interact with the system

**** What does cl-hab currently do

***** cl-hab consists of the following components:

- items: items are a primitive to represent the temperatur of a sensor, the state of light in your house, the state of you window being open or closed, etc.
- persistence: persistences allow to persist and load the state of items. Currently two types of persistences are supported:
  - simple-persistence that just stores the current state and can retrieve it
  - historic persiastence with a support for influxdb to store each changed item value in influxdb and also retrieve values for a specific time range to calculate averages, peaks or whatever.

    
